name: Unit Test
on: [push, pull_request]

jobs:
  test-kindly:
    name: Test with Go v${{ matrix.go-version }} and KinD ${{ matrix.kind-version }}
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        kind-version: [v0.7.0]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: engineerd/setup-kind@v0.7.0
      with:
          version: "${{ matrix.kind-version }}"

    - name: Check Kubernetes on KinD
      run: |
        kubectl cluster-info
        kubectl get all -A

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: Check Go code format
      run: make check-fmt
    
    - name: Test
      run: make test
